name: jose-jwk

on:
  pull_request:
    paths:
      - ".github/workflows/jose-jwk.yml"
      - "jose-b64/**"
      - "jose-jwa/**"
      - "jose-jwk/**"
      - "Cargo.*"
  push:
    branches:
      - master

defaults:
  run:
    working-directory: jose-jwk

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  minimal-versions:
    uses: RustCrypto/actions/.github/workflows/minimal-versions.yml@master
    with:
        working-directory: ${{ github.workflow }}

  no_std:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.rust }}
      - run: cargo build --target ${{ matrix.target }} --no-default-features

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
        features:
          # Test no features, individual features and all features.
          - ""
          - crypto
          - p256
          - p384
          - rsa
          - url
          - p256,p384,rsa,url

          # Test all combinations of crypto enablement
          - p256,p384
          - p256,rsa
          - p384,p256
          - p384,rsa
          - rsa,p256
          - rsa,p384
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --no-default-features --features=${{ matrix.features }}
